### ISSUE TITLE
Support other languages (e.g. Go, Rust, C#)

### ISSUE THREAD

**Issue by lostintangent** [lostintangent/codeswing#10]
Currently, CodeSwing supports web-based languages, but depending on user-interest, it would make sense to add support for other languages as well. If folks are finding CodeSwing useful, and are interested in another language, I'd love to hear that feedback!

**Comment by cocowalla** [comment]
Would love to see C# support!

**Comment by lostintangent** [comment]
Closing this for now, since I haven't heard enough demand for it. I'll re-open in the future if/as the community would like to see this.
