### ISSUE TITLE
Toolbar is missing 

### ISSUE THREAD

**Issue by andrewwhiteingale** [lostintangent/codeswing#102]
When I make or open the project the entire toolbar is just gone:( Any solution?

**Comment by andrewwhiteingale** [comment]
codeswing doesnm't work.

**Comment by mikedpad** [comment]
It's not working with the latest VSCode. You'll need to roll back until they update it.

See here: https://github.com/lostintangent/codeswing/issues/101#issuecomment-2273337751

**Comment by andrewwhiteingale** [comment]
thanks

**Comment by lostintangent** [comment]
This has now been fixed with the latest version of CodeSwing
