### ISSUE TITLE
Request: LESS/SASS Preview Output

### ISSUE THREAD

**Issue by ryandejaegher** [lostintangent/codeswing#42]
I know that CodeSwing supports LESS and SASS, would it be possible to show a preview of the output? Similar to the way that CodePen lets you toggle to view the compiled output.

**Comment by lostintangent** [comment]
Hey! I'm tracking this feature via #5, which would allow you to view the generated output for any compiled language. So I'll close this as a duplicate and we can use that issue to track progress. Thanks!
