### ISSUE TITLE
Importing react component from gist file

### ISSUE THREAD

**Issue by Sheraff** [lostintangent/codeswing#45]
With the codeswing.json setting `"scriptType": "module"`, we can easily import a JS module from another one. For example:

```
|- charsets.js
|- script.mjs
|- index.html
|- style.css
```
```js
// script.mjs
import { test } from './charsets.js'
```

In the same vein, I'd love to be able to import a react component from a .jsx file

```
|- MyComponent.jsx
|- App.jsx
```
```jsx
// App.jsx
import MyComponent from './MyComponent.jsx'
```

**Comment by lostintangent** [comment]
Hey! I actually implemented this recently, and just need to ship it 😎

**Comment by lostintangent** [comment]
This has now been shipped!
