### ISSUE TITLE
Renaming file renames the wrong file

### ISSUE THREAD

**Issue by Sheraff** [lostintangent/codeswing#49]
Using 
- vscode 1.57.1
- latest codeswing 0.0.20
- latest gistpad 0.3.0

Reproduce
- create a gistpad swing HTML/JS/CSS
- rename style.css to style.scss
- another file gets renamed instead (sometimes script.js, sometimes index.html, IDK what influences that)

Here's a screencast of the issue

https://user-images.githubusercontent.com/1325721/125069194-b62cef80-e0b6-11eb-994d-42ac69cd73a3.mov

**Comment by lostintangent** [comment]
Yeah this is actually an issue with GistPad, not CodeSwing. I've noticed that Gist file renaming can be super funky and I'm not sure if it's a GistPad bug or a Gist bug. Let me take a look!

**Comment by lostintangent** [comment]
I confirmed that this is unfortunately an issue that can sometimes happen with the Gist API. CodeSwing itself doesn't manage file renames. It simply asks the underlying file system provider to do the rename for it, and in the case of gists, that can sometimes fail. I'm going to close this issue, and try to investigate the issue further on the GistPad side. Thanks!
