### ISSUE TITLE
Feature Request - Import from CodePen URL

### ISSUE THREAD

**Issue by Pawper** [lostintangent/codeswing#53]
It would be awesome to import from a CodePen URL.

**Comment by lostintangent** [comment]
I'm not sure if CodePen has an API to make this possible today. However, what you can do is:

1. Export a pen to a GitHub Gist
2. Install the [GistPad](https://aka.ms/gistpad) extension and sign into the same GitHub identity you used when exporting the pen
3. You'll then see the pen in the `Gists` tree view, and if you open it, it will detect that you have CodeSwing installed, and open the swing editor

The nice thing about that flow, is that you can also create new swings in VS Code and store them in gists. That way, you have your swings more easily shareable.

**Comment by lostintangent** [comment]
After looking into this more, there unfortunately isn't an API to support this scenario, and so I'm going to close it as non actionable. That said, per my previous comment, the workaround is to expose a pen to a gist and then use GistPad to open it. Thanks!
