### ISSUE TITLE
In the console, output of variables doesn't appear

### ISSUE THREAD

**Issue by ItalyPaleAle** [lostintangent/codeswing#58]
Create a JS Swing and type the code below:

```js
const test = 'aaa'
console.log('test', test)
```

In the browser's dev tools, it shows `test aaa` but in CodeSwing's output, it only shows `test`.

This happens in VS Code for the Web (vscode.dev/github.dev)

**Comment by lostintangent** [comment]
CodeSwing monkey patches "console.log" and I don't think it currently implements the multi-argument format. But they should be pretty straight forward to add! I'll take a look tomorrow 👍
