### ISSUE TITLE
Referencing type declarations

### ISSUE THREAD

**Issue by TFTomSun** [lostintangent/codeswing#69]
I would like to import / reference the type declarations of this package:
https://www.npmjs.com/package/@types/fabric

The unpkg url is:
https://unpkg.com/@types/fabric@4.5.7/index.d.ts

I didn't find any possibility how this can be achieved. When I try to add the library as module, it isn't found.

**Comment by jasonwilliams** [comment]
This sounds related to https://github.com/lostintangent/codeswing/issues/25

**Comment by lostintangent** [comment]
In the next release, you won't need to explicitly reference type definitions, since they'll be referenced automatically
